spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pokemon_db
    username: pokemon
    password: pokemon
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    user:
      name: admin
      password: secret

server:
  port: 8080